#!/usr/bin/env bash
# Regenerate helper/mvec_deadzone_spv.h from helper/shaders/mvec_deadzone.comp.
# Needs glslang (https://github.com/KhronosGroup/glslang releases, or the
# distro 'glslang' package). The generated header is committed, so build.sh
# does not require glslang.
set -euo pipefail
cd "$(dirname "$0")/.."

GLSLANG="${GLSLANG:-$(command -v glslang || command -v glslangValidator || true)}"
[ -n "$GLSLANG" ] || { echo "glslang not found (set GLSLANG=/path/to/glslang)" >&2; exit 1; }

out="$(mktemp -t mvec_deadzone.XXXXXX.spv)"
trap 'rm -f "$out"' EXIT
"$GLSLANG" helper/shaders/mvec_deadzone.comp -V -o "$out"

{
    echo "// Generated by tools/gen_mvec_spv.sh from helper/shaders/mvec_deadzone.comp."
    echo "// GPU NVOF post-pass: decode + deadzone clamp + grid->full-res upscale."
    echo "#pragma once"
    echo "#include <cstdint>"
    echo "static const uint32_t kMVecDeadzoneSpv[] = {"
    od -An -tu4 -v "$out" | tr -s ' ' '\n' | grep -v '^$' | \
        awk '{printf "%s,", $0; if (++n % 12 == 0) printf "\n"} END {printf "\n"}'
    echo "};"
    echo "static const size_t kMVecDeadzoneSpvLen = sizeof(kMVecDeadzoneSpv) / sizeof(kMVecDeadzoneSpv[0]);"
} > helper/mvec_deadzone_spv.h
echo "wrote helper/mvec_deadzone_spv.h ($(wc -c < "$out") bytes SPIR-V)"