#!/usr/bin/env bash
# Regenerate layer_linux/src/shaders/meter_reduce_spv.h from
# layer_linux/src/shaders/meter_reduce.comp.
#
# Needs glslang (the distro 'glslang' package or a release), or build/glsl2spv
# (built separately) which dlopens libshaderc_shared. The generated header is
# committed, so the normal Meson build does not require either one.
set -euo pipefail
cd "$(dirname "$0")/.."

GLSLANG="${GLSLANG:-$(command -v glslang || command -v glslangValidator || true)}"
if [ -n "$GLSLANG" ]; then
    compile() { "$GLSLANG" "$1" -V -o "$2"; }
elif [ -x build/glsl2spv ]; then
    compile() { build/glsl2spv "$1" "$2"; }
else
    echo "neither glslang nor build/glsl2spv found (build glsl2spv first or set GLSLANG=/path)" >&2
    exit 1
fi

src="layer_linux/src/shaders/meter_reduce.comp"
out="$(mktemp -t meter_reduce.XXXXXX.spv)"
trap 'rm -f "$out"' EXIT
compile "$src" "$out"

{
    echo "// Generated by tools/gen_meter_spv.sh from layer_linux/src/shaders/meter_reduce.comp."
    echo "// GPU white-point meter: tile max -> histogram -> 90th percentile -> resolve."
    echo "#pragma once"
    echo "#include <cstdint>"
    echo "static const uint32_t kMeterReduceSpv[] = {"
    od -An -tu4 -v "$out" | tr -s ' ' '\n' | grep -v '^$' | \
        awk '{printf "%s,", $0; if (++n % 12 == 0) printf "\n"} END {printf "\n"}'
    echo "};"
    echo "static const size_t kMeterReduceSpvLen = sizeof(kMeterReduceSpv) / sizeof(kMeterReduceSpv[0]);"
} > layer_linux/src/shaders/meter_reduce_spv.h
echo "wrote layer_linux/src/shaders/meter_reduce_spv.h ($(wc -c < "$out") bytes SPIR-V)"
