#!/usr/bin/env bash
# Regenerate helper/mvec_deadzone_spv.h from helper/shaders/mvec_deadzone.comp.
#
# Two variants come out of one source: FLOW_FIXED5=1 decodes
# R16G16_SFIXED5_NV texels, FLOW_FIXED5=0 decodes R16G16_SFLOAT half bits.
# The format is a compile-time choice because a specialization-constant branch
# in this shader mispredicted on the NVIDIA driver (see the shader header).
#
# Needs glslang (https://github.com/KhronosGroup/glslang releases, or the
# distro 'glslang' package). Without the CLI, tools/glsl2spv -- built by
# glsl2spv -- dlopens libshaderc_shared and fills the same role. The generated
# header is committed, so the normal Meson build does not require either one.
set -euo pipefail
cd "$(dirname "$0")/.."

GLSLANG="${GLSLANG:-$(command -v glslang || command -v glslangValidator || true)}"
if [ -n "$GLSLANG" ]; then
    compile() { "$GLSLANG" "$1" -V -D "$2" -o "$3"; }
elif [ -x build/glsl2spv ]; then
    compile() { build/glsl2spv "$1" "$3" -D "$2"; }
else
    echo "neither glslang nor build/glsl2spv found (build glsl2spv first or set GLSLANG=/path)" >&2
    exit 1
fi

src="helper/shaders/mvec_deadzone.comp"
out5="$(mktemp -t mvec_deadzone_fixed5.XXXXXX.spv)"
outf="$(mktemp -t mvec_deadzone_float.XXXXXX.spv)"
trap 'rm -f "$out5" "$outf"' EXIT
compile "$src" FLOW_FIXED5=1 "$out5"
compile "$src" FLOW_FIXED5=0 "$outf"

emit_array() { # emit_array <spv> <array-name>
    echo "static const uint32_t $2[] = {"
    od -An -tu4 -v "$1" | tr -s ' ' '\n' | grep -v '^$' | \
        awk '{printf "%s,", $0; if (++n % 12 == 0) printf "\n"} END {printf "\n"}'
    echo "};"
    echo "static const size_t ${2}Len = sizeof($2) / sizeof($2[0]);"
}

{
    echo "// Generated by tools/gen_mvec_spv.sh from helper/shaders/mvec_deadzone.comp."
    echo "// GPU NVOF post-pass: decode + deadzone clamp + grid->full-res upscale."
    echo "// Two compile-time flow-format variants; pick by the session's flow format."
    echo "#pragma once"
    echo "#include <cstdint>"
    emit_array "$out5" kMVecDeadzoneSpvFixed5
    emit_array "$outf" kMVecDeadzoneSpvFloat
} > helper/mvec_deadzone_spv.h
echo "wrote helper/mvec_deadzone_spv.h (fixed5 $(wc -c < "$out5") bytes, float $(wc -c < "$outf") bytes SPIR-V)"
